import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Auth',
  description: 'Generated by create next app',
}

export default function Auth({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <section>{children}</section>
  )
}
