"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Input } from "@/components/Input";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import {
  AiFillHeart,
  AiFillHome,
  AiOutlineMenu,
  AiOutlineSearch,
  AiOutlineUnlock,
} from "react-icons/ai";
import { BsFillPlayFill, BsFillStopwatchFill } from "react-icons/bs";
import { FaReact } from "react-icons/fa";
import {
  MdKeyboardArrowDown,
  MdNotificationsNone,
  MdOutlineAddBox,
} from "react-icons/md";
import { IoMdNotificationsOutline } from "react-icons/io";
import { RiLogoutBoxRFill } from "react-icons/ri";
import ActiveLink from "@/components/ActiveLink";
import Sidebar from "@/components/Sidebar";
import TopBar from "@/components/TopBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [showNav, setShowNav] = useState(true);
  const [isMobile, setIsMobile] = useState(false);

  const handdleSize = () => {
    if (innerWidth <= 640) {
      setShowNav(false);
      setIsMobile(true);
    } else {
      setShowNav(true);
      setIsMobile(false);
    }
  };

  useEffect(() => {
    if (typeof window != undefined) {
      window.addEventListener("resize", handdleSize);
    }
    return () => {
      removeEventListener("resize", handdleSize);
    };
  }, []);

  return (
    <html lang="en">
      <body className="bg-gray-900">
        <main >
          
          <Sidebar showNav={showNav} isMobile={isMobile} />
          <TopBar setShowNav={setShowNav} showNav={showNav}/>

          

          {/* conteudo aqui */}

          <div
              className={`pt-24 w-full pl-28  text-white duration-300 transition-all 
              ${showNav && !isMobile ? "pl-[350px]" : ""} 
            
              `}
            >
              <div className="bg-red-100 pr-4">{children} lore</div>
              
            
            </div>
        </main>
      </body>
    </html>
  );
}
