"use client";

import type { Metadata } from "next";

import { useEffect, useState } from "react";

import Sidebar from "@/components/Sidebar";
import TopBar from "@/components/TopBar";
import { MdKeyboardArrowLeft, MdKeyboardArrowRight } from "react-icons/md";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [showNav, setShowNav] = useState(true);
  const [isMobile, setIsMobile] = useState(false);

  const handdleSize = () => {
    if (innerWidth <= 640) {
      setShowNav(false);
      setIsMobile(true);
    } else {
      setShowNav(true);
      setIsMobile(false);
    }
  };

  const slideLeft = ()=> {
    var slide = document.getElementById('slideRef') /// usar um ref aqui 
    console.log('opa')
    if(!slide) return

    slide.scrollLeft = slide.scrollLeft - 200
  }
  const slideRight = ()=> {
    var slide = document.getElementById('slideRef') /// usar um ref aqui 

    if(!slide) return

    slide.scrollLeft = slide.scrollLeft + 200
  }


  useEffect(() => {
    if (typeof window != undefined) {
      window.addEventListener("resize", handdleSize);
    }
    return () => {
      removeEventListener("resize", handdleSize); // CleanerUp
    };
  }, []);

  return (
    <>
      <Sidebar showNav={showNav} isMobile={isMobile} />
      <TopBar setShowNav={setShowNav} showNav={showNav} />

      {/* conteudo aqui */}

      <main
        className={`pt-32 w-full pl-28   text-white duration-300 transition-all 
              ${showNav && !isMobile ? "pl-[320px]" : ""} 
            
              `}
      >
        <div className="w-full h-full flex  flex-col gap-5">
          <div className=" h-full flex pr-11 ">
            <div onClick={slideLeft} className=" h-full py-5 bg-gray-900  rounded  hover:bg-gray-500 text-white  cursor-pointer">
              <MdKeyboardArrowLeft />
            </div>
            <div id='slideRef' className="relative overflow-x-scroll scroll whitespace-nowrap scroll-smooth scrollbar-none">
              <ul className="flex gap-6 ">
                <li className="text-white rounded-2xl hover:opacity-80  cursor-pointer bg-gray-800 px-7 py-4">
                  Element
                </li>
                <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                  Element
                </li>
                <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                  Element
                </li>
                <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                  Element
                </li>
                <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                  Element
                </li>
                <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                  Element
                </li>
                <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                  Element
                </li>
                <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                  Element
                </li>
                <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                  Element
                </li>
                <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                  Element
                </li>
                <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                  Element
                </li>
                <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                  Element
                </li>
                <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                  Element
                </li>
                <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                  Element
                </li>
              </ul>
            </div>
            <div onClick={slideRight} className="h-full py-5 bg-gray-900  rounded  hover:bg-gray-500 text-white  cursor-pointer">
              <MdKeyboardArrowRight />
            </div>
          </div>

          <div className=" w-full">{children}</div>
        </div>
      </main>
    </>
  );
}
