"use client";

import type { Metadata } from "next";

import { useEffect, useState } from "react";

import Sidebar from "@/components/Sidebar";
import TopBar from "@/components/TopBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [showNav, setShowNav] = useState(true);
  const [isMobile, setIsMobile] = useState(false);

  const handdleSize = () => {
    if (innerWidth <= 640) {
      setShowNav(false);
      setIsMobile(true);
    } else {
      setShowNav(true);
      setIsMobile(false);
    }
  };

  useEffect(() => {
    if (typeof window != undefined) {
      window.addEventListener("resize", handdleSize);
    }
    return () => {
      removeEventListener("resize", handdleSize);
    };
  }, []);

  return (
    <>
      <Sidebar showNav={showNav} isMobile={isMobile} />
      <TopBar setShowNav={setShowNav} showNav={showNav} />

      {/* conteudo aqui */}

      <main
        className={`pt-24 w-full pl-28  text-white duration-300 transition-all 
              ${showNav && !isMobile ? "pl-[350px]" : ""} 
            
              `}
      >
        <div className="bg-red-100 pr-4">{children}</div>
      </main>
    </>
  );
}
