"use client";

import type { Metadata } from "next";

import { useEffect, useState } from "react";

import Sidebar from "@/components/Sidebar";
import TopBar from "@/components/TopBar";
import { MdKeyboardArrowLeft, MdKeyboardArrowRight } from "react-icons/md";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [showNav, setShowNav] = useState(true);
  const [isMobile, setIsMobile] = useState(false);

  const handdleSize = () => {
    if (innerWidth <= 640) {
      setShowNav(false);
      setIsMobile(true);
    } else {
      setShowNav(true);
      setIsMobile(false);
    }
  };

  useEffect(() => {
    if (typeof window != undefined) {
      window.addEventListener("resize", handdleSize);
    }
    return () => {
      removeEventListener("resize", handdleSize);
    };
  }, []);

  return (
    <>
      <Sidebar showNav={showNav} isMobile={isMobile} />
      <TopBar setShowNav={setShowNav} showNav={showNav} />

      {/* conteudo aqui */}

      <main
        className={`pt-32 w-full pl-28   text-white duration-300 transition-all 
              ${showNav && !isMobile ? "pl-[320px]" : ""} 
            
              `}
      >
        <div className="w-full flex  flex-col gap-5">
          <div className="pr-4 ">
          <div className="  relative overflow-hidden ">
            <ul className="flex gap-6 ">
              <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                Element
              </li>
              <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                Element
              </li>
              <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                Element
              </li>
              <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                Element
              </li>
              <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                Element
              </li>
              <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                Element
              </li>
              <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                Element
              </li>
              <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                Element
              </li>
              <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                Element
              </li>
              <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                Element
              </li>
              <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                Element
              </li>
              <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                Element
              </li>
              <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                Element
              </li>
              <li className="text-white rounded-2xl hover:opacity-80 cursor-pointer bg-gray-800 px-7 py-4">
                Element
              </li>
            </ul>

            {/* controles */}
            {/* <div className="absolute top-0 -left-0 bg-gray-900 px-1 rounded h-full hover:bg-gray-500 text-white flex justify-center items-center cursor-pointer">
              <MdKeyboardArrowLeft />
            </div> */}
            <div className="absolute top-0 right-0 bg-gray-900 px-1 rounded h-full hover:bg-gray-500 text-white flex justify-center items-center cursor-pointer">
              <MdKeyboardArrowRight />
            </div>
          </div>


          </div>
         
          <div className=" w-full">
          {children}
          </div>
        </div>
      </main>
    </>
  );
}
